In [2]:
import numpy as np

Ejercicio 1
Crea 3 nuevos arrays.
Array de tipo entero, que contenga solo los números impares del 1 al 100.
Array de tipo cadena con tu nombre y apellidos
Array de tipo fechas, que contenga todos los días desde el 01Enero2020 al 04Febrero2020

In [3]:
impares = np.arange(1, 100, 2)
impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [4]:
name = np.array(["adrian" , " prz " , " cb"])
name

array(['adrian', ' prz ', ' cb'], dtype='<U6')

In [5]:
name.dtype

dtype('<U6')

In [6]:
_ = np.arange(1,100)
array_impares = _[_ % 2 != 0]
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [7]:
fechas = np.arange('2022-01-01', '2022-02-04', dtype='datetime64[D]')
fechas

array(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
       '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
       '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
       '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
       '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20',
       '2022-01-21', '2022-01-22', '2022-01-23', '2022-01-24',
       '2022-01-25', '2022-01-26', '2022-01-27', '2022-01-28',
       '2022-01-29', '2022-01-30', '2022-01-31', '2022-02-01',
       '2022-02-02', '2022-02-03'], dtype='datetime64[D]')

### Ejercicio 2

Recupera los últimos 10 elementos del array de impares

In [10]:
imparess = impares[:len(impares)-11:-1]
imparess

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81])

### Ejercicio 3

Recorre el array de fechas, y genera un nuevo numpy array que contenga unicamente los días laborales

In [11]:
laborables = []
for fecha in fechas:
    if np.is_busday(fecha):
        laborables.append(fecha)
laborables_array = np.array(laborables, dtype = 'datetime64')

laborables_array

array(['2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06',
       '2022-01-07', '2022-01-10', '2022-01-11', '2022-01-12',
       '2022-01-13', '2022-01-14', '2022-01-17', '2022-01-18',
       '2022-01-19', '2022-01-20', '2022-01-21', '2022-01-24',
       '2022-01-25', '2022-01-26', '2022-01-27', '2022-01-28',
       '2022-01-31', '2022-02-01', '2022-02-02', '2022-02-03'],
      dtype='datetime64[D]')

In [13]:
fechas[np.is_busday(fechas)]


array(['2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06',
       '2022-01-07', '2022-01-10', '2022-01-11', '2022-01-12',
       '2022-01-13', '2022-01-14', '2022-01-17', '2022-01-18',
       '2022-01-19', '2022-01-20', '2022-01-21', '2022-01-24',
       '2022-01-25', '2022-01-26', '2022-01-27', '2022-01-28',
       '2022-01-31', '2022-02-01', '2022-02-02', '2022-02-03'],
      dtype='datetime64[D]')

### Ejercicio 4

Genera la siguiente matriz.

$A = \begin{pmatrix}
10 & 1 & 8 & 4 \\
3 & 7 & 2 & 1 \\
0 & 2 & 20 & 12 \\
\end{pmatrix}$

¿De qué tipo es?
Luego, implementa una máscara a todos los números de la matriz mayores o iguales a 10

In [14]:
A = np.matrix('10 1 8 4 ; 3 7 2 1 ; 0 2 20 12')
A

matrix([[10,  1,  8,  4],
        [ 3,  7,  2,  1],
        [ 0,  2, 20, 12]])

In [15]:
A.dtype

dtype('int32')

In [16]:
import numpy.ma as ma

A_masked = ma.masked_greater_equal(A, 10)
A_masked

masked_matrix(
  data=[[--, 1, 8, 4],
        [3, 7, 2, 1],
        [0, 2, --, --]],
  mask=[[ True, False, False, False],
        [False, False, False, False],
        [False, False,  True,  True]],
  fill_value=999999)

Crea dos fechas, la primera de ellas será tu fecha de nacimiento, y la segunda, la de un familiar o amigo tuyo.

- ¿Qué diferencia en horas hay entre las dos fechas?
- ¿Cual sería tu fecha de nacimiento si hubieras nacido 236 horas antes?

In [25]:
fecha1 = np.datetime64('1993-05-03')
fecha2 = np.datetime64('1985-12-11')

fechadif = fecha1 - fecha2
print(fechadif)
np.timedelta64(fechadif, 'h')

2700 days


numpy.timedelta64(64800,'h')

In [23]:
print(f"él es {str(np.timedelta64(fechadif, 'h'))} horas mayor que yo")

él es 64800 hours horas mayor que yo


In [24]:
h = np.timedelta64(236, 'h')
nueva_fechnaci = fecha1 - h
print(f"La fecha de nacimiento de él sería {str(nueva_fechnaci)}")

La fecha de nacimiento de él sería 1993-04-23T04
