In [5]:
import numpy as np

In [6]:
a = np.array([1 , 3 ,4 , 6] , dtype=np.int_ )
a

array([1, 3, 4, 6])

In [7]:
a.dtype

dtype('int32')

In [8]:
bool_array = np.array([[1, 0 , 1 , 0] , [1 , 0 , 1 , 1]] , dtype=np.bool)
bool_array

C:\Users\Usuario\AppData\Local\Temp\ipykernel_4456\2528677511.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  bool_array = np.array([[1, 0 , 1 , 0] , [1 , 0 , 1 , 1]] , dtype=np.bool)


array([[ True, False,  True, False],
       [ True, False,  True,  True]])

In [9]:
True * False

0

In [13]:
char_array = np.array(['a' , 'b' , 'c'] ,dtype=np.chararray)
char_array

array(['a', 'b', 'c'], dtype=object)

In [14]:
type(char_array)


numpy.ndarray

In [15]:
from sys import getsizeof

a = np.array([1 , 2 , 3 ,4 ], dtype=np.int8)
b = np.array([1 , 2 , 3 , 4], dtype=np.int64)

print('A' , getsizeof(a))
print('B' , getsizeof(b))

A 108
B 136


In [16]:
a.dtype

dtype('int8')

In [18]:
a.dtype.type is np.int8

True

In [19]:
# np.nan

np.nan

nan

In [21]:
np.isnan(np.nan)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [22]:
np.array([1 , 2 ,3 , np.nan , 4])

array([ 1.,  2.,  3., nan,  4.])

In [23]:
## matrix
m = np.matrix('1 , 2 , 3 ; 4 , 5 6' , dtype=np.float16)
m

matrix([[1., 2., 3.],
        [4., 5., 6.]], dtype=float16)

In [24]:
a = np.array([[1,2 , 3], [4 , 5 , 6]] , dtype=np.float16)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [25]:
m = np.asmatrix(a)
m

matrix([[1., 2., 3.],
        [4., 5., 6.]], dtype=float16)