In [1]:
import numpy as np

In [2]:
a = np.array([[3, 2], [1, 3]])
b = np.array([[2, 2], [1, 2]])

$A = \begin{pmatrix}
3 & 2 \\
1 & 3 \\
\end{pmatrix}$
$B = \begin{pmatrix}
2 & 2 \\
1 & 2 \\
\end{pmatrix}$
$AxB = \begin{pmatrix}
8 & 10 \\
5 & 8 \\
\end{pmatrix}$

In [3]:
# Producto matricial de dos matrices
np.dot(a, b)

array([[ 8, 10],
       [ 5,  8]])

In [4]:
# vdot - Devuelve el producto escalar de dos vectores.
np.vdot(a,b)

17

El calculo de arriba sería: 3\*2 + 2\*2 + 1\*1 + 3\*2 = 17

In [5]:
# inner - Producto interno de dos matrices.
a = np.arange(6).reshape((2,3))
b = np.arange(3)

In [6]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
b

array([0, 1, 2])

In [8]:
np.inner(a, b)

array([ 5, 14])

El calculo sería: 
- 0 x 0 + 1 x 1 + 2 x 2 = 5
- 3 x 0 + 4 x 1 + 5 x 1 = 14

In [9]:
# matrix_power - Eleve una matriz cuadrada a la potencia (entera) n.
m = np.array([[2,3], [1,4]])
np.linalg.matrix_power(m, 2)

array([[ 7, 18],
       [ 6, 19]])

La matriz m^2 es igual a el producto escalar de m x m. Podemos comprobar el resultado con *np.dot*

In [10]:
np.dot(m,m)

array([[ 7, 18],
       [ 6, 19]])

In [11]:
# eig - Calcula los valores propios y los vectores propios rectos de una matriz cuadrada
m = np.diag([4,3,2,1])
m

array([[4, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

In [12]:
np.linalg.eig(m)

(array([4., 3., 2., 1.]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [13]:
# det - Calcula el determinante de una matriz.

In [14]:
np.linalg.det(m)

24.000000000000004

In [15]:
# solve - Resuelve una ecuación con matrices
a

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
b

array([0, 1, 2])

In [17]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

El calculo de arriba sería:
- 3 \* x0 + 1 \* x1 = 9
- 1 \* x0 + 2 \* x1 = 8