In [1]:
import numpy as np

In [2]:
# all - Comprueba si todos los elementos de una matriz o array cumplen una condicion

a = np.array([2,3,4,5])
np.all(a < 10)

True

In [3]:
# any - Comprueba si algún elemento de una matriz o array cumplen una condicion

a = np.array([2,3,4,5])
np.any(a < 0)

False

In [4]:
# logical_and : Función lógica and. Devuelve True si todas las comprobaciones son ciertas
np.logical_and(a > 2, a < 4)

array([False,  True, False, False])

In [5]:
# logical_or : Función lógica or. Devuelve True si alguna de las comprobaciones son ciertas
np.logical_or(a > 2, a < 4)

array([ True,  True,  True,  True])

In [6]:
# Devuelve True si todas las diferencia en valor absoluto es menor a la tolerancia.
np.allclose([1e10,1e-7], [1.00001e10,1.000001e-7], rtol=0.00001)

True

In [7]:
#isclose - Igual, pero valor a valor
np.isclose([1e10,1e-7], [1.001e10,1.000001e-7], rtol=0.00001)

array([False,  True])

In [8]:
#equal - Verdadero si dos arrays o matrices son iguales en cuanto a dimensiones y valores
np.array_equal(np.array([1,2,3]), np.array([1,2,3]))

True

In [9]:
np.array_equal(np.array([1,2,3]), np.array([1,2,3,4]))

False

In [10]:
# greater - Devuelve True si el valor es mayor.
np.greater(np.array([1,2,3]), np.array([3,2,1]))

array([False, False,  True])

In [11]:
np.greater_equal(np.array([1,2,3]), np.array([3,2,1]))

array([False,  True,  True])

In [12]:
# less y less_equal funcionan igual.
np.less(np.array([1,2,3]), np.array([3,2,1]))

array([ True, False, False])

In [13]:
np.less_equal(np.array([1,2,3]), np.array([3,2,1]))

array([ True,  True, False])