In [1]:
import numpy as np

Las funciones estadísticas también son realmente interesantes. Son bastante usadas cualquier analísis de datos

### Funciones relacionadas con el orden

In [2]:
# min y max devuelven los valores minimos y maximos de un array
a = np.array([2,5,6,10])
print("Min", np.min(a))
print("Max", np.max(a))

Min 2
Max 10


In [3]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.min(b, axis = 1) # Axis 1 por filas

array([0, 4, 8])

In [5]:
np.min(b, axis = 0) # Axis 0 por columnas

array([0, 1, 2, 3])

In [6]:
# percentile - Calcule el percentil q-ésimo de los datos a lo largo del eje especificado.
b = np.arange(0, 101)
b


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
np.percentile(b, q = 11)

11.0

In [8]:
# Idem para el quantil. 

In [9]:
np.quantile(b, q = 0.25)

25.0

### Medias y varianzas

In [10]:
# median - Calcula la mediana (valor central)
np.median(b)

50.0

In [11]:
np.median(np.array([1,2,0,100,200,300,50]))

50.0

In [12]:
# average o media (con pesos)
a = np.array([1,2,3,4])
np.average(a)

2.5

In [13]:
np.average(a, weights=[2,2,1,1])

2.1666666666666665

La cuenta sería:
avg = sum(a * pesos) / sum(pesos)

1 x 2 + 2 x 2 + 3 x 1 + 4 x 1 = 13 &rarr; 13 / 6 = 2.16

In [14]:
# mean - Practicamente idéntico
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.mean(b, axis = 0) # Media por columnas

array([4.5, 5.5, 6.5])

In [16]:
np.mean(b, axis = 1) # Media por filas

array([ 1.,  4.,  7., 10.])

In [17]:
# std - Desviacion estándar
np.std(b, axis = 0)

array([3.35410197, 3.35410197, 3.35410197])

In [18]:
np.std(b)

3.452052529534663

La desviación estándar es la raíz cuadrada del promedio de las desviaciones al cuadrado de la media, es decir: 

std = sqrt(mean(abs(x - x.mean())\**2))

In [19]:
# var - Varianza
np.var(b, axis = 1)

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])

La varianza es el promedio de las desviaciones cuadradas de la media, es decir: 

var = mean (abs (x - x.mean ()) \** 2).

**La desviación estándar es la raiz cuadrada de la varianza.**

In [20]:
std = np.std(b, axis = 0)
print(std)
var = np.var(b, axis = 0)
print(var)

[3.35410197 3.35410197 3.35410197]
[11.25 11.25 11.25]


In [21]:
np.sqrt(var)

array([3.35410197, 3.35410197, 3.35410197])