In [1]:
import numpy as np

### Redondeo

In [2]:
a = 2.49264

In [3]:
# round - Redonde un número a las cifras que definamos
np.round(a, 1)

2.5

In [4]:
array = np.array([1.435, 13.1435, 4.916])
np.round(array, 2)

array([ 1.44, 13.14,  4.92])

In [5]:
# floor - Devuelve el suelo - el número entero pequeño más cercano
np.floor(array)

array([ 1., 13.,  4.])

In [6]:
# Devuelve el techo - el siguiente número entero
np.ceil(array)

array([ 2., 14.,  5.])

### Sumas y productos

In [7]:
# prod - Devuelve el producto de los elementos de la matriz sobre un eje dado
b = np.array([2,3,4])
np.prod(b)

24

In [8]:
b = np.array([[2,3,4],[2,2,2]])
np.prod(b, axis = 0)

array([4, 6, 8])

In [9]:
np.prod(b, axis = 1)

array([24,  8])

In [10]:
# sum - Mismo funcionamiento que prod, pero en este caso realizando la suma

In [11]:
np.sum(b)

15

In [12]:
np.sum(b, axis = 0)

array([4, 5, 6])

In [13]:
np.sum(b, axis = 1)

array([9, 6])

### Exponentes y logaritmos

In [14]:
#exp - Calcula el exponencial de todos los elementos en la matriz de entrada.
b

array([[2, 3, 4],
       [2, 2, 2]])

In [15]:
np.exp(b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

El exponencial se calcula como el número e elevado al escalar. Es decir, es equivalente a:

In [16]:
np.power(np.e, b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

Para el cálculo de logaritmos tenemos las opciones:
- log: base e
- log10: base 10
- log2: base 2

In [17]:
p = np.power(np.e, b)
np.log(p)

array([[2., 3., 4.],
       [2., 2., 2.]])

In [18]:
np.log10(b)

array([[0.30103   , 0.47712125, 0.60205999],
       [0.30103   , 0.30103   , 0.30103   ]])

In [19]:
np.power(10, np.log10(b))

array([[2., 3., 4.],
       [2., 2., 2.]])

In [20]:
np.log2(b)

array([[1.       , 1.5849625, 2.       ],
       [1.       , 1.       , 1.       ]])

In [21]:
np.power(2, np.log2(b))

array([[2., 3., 4.],
       [2., 2., 2.]])

### Operaciones aritméticas

Hacen referencia a operaciones básicas de suma, resta, multiplicación o división de cada elemento del array.

In [22]:
a = np.array([[1,2,3,4], [4,3,2,1]])
b = np.array([4,3,2,1])

In [23]:
# Suma
np.add(a,b)

array([[5, 5, 5, 5],
       [8, 6, 4, 2]])

In [24]:
# Resta
np.subtract(a,b)

array([[-3, -1,  1,  3],
       [ 0,  0,  0,  0]])

In [25]:
# Multiplicacion
np.multiply(a,b)

array([[ 4,  6,  6,  4],
       [16,  9,  4,  1]])

In [26]:
# Division
np.divide(a,b)

array([[0.25      , 0.66666667, 1.5       , 4.        ],
       [1.        , 1.        , 1.        , 1.        ]])