In [34]:
import numpy as np

In [35]:
# shape - Recuperas la dimension
a = np.array([[1,2,3,4], [4,3,2,1]])
a.shape

(2, 4)

In [36]:
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [37]:
# reshape - Modificar la dimension
a.reshape((4,2))

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [38]:
a.ravel()

array([1, 2, 3, 4, 4, 3, 2, 1])

In [39]:
# T - Transpone filas y columnas
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [40]:
a.T


array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

In [41]:
# asarray - Convierte una lista python en numpy array
np.asarray([1,2,3,4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [42]:
# asfarray - Igual, pero devuelve el array de tipo float
np.asfarray([1,2,3,4])

array([1., 2., 3., 4.])

In [43]:
np.asfarray([1,2,3,4], dtype = np.int8)


array([1., 2., 3., 4.])

In [44]:
# asarray_chkfinite - Convierte la entrada en un array, verificando NaN o Infs.

a = [1,2,3,4, np.nan]
np.asarray_chkfinite(a)

ValueError: array must not contain infs or NaNs

In [ ]:
# repeat - Genera un array de números iguales
a = np.repeat(a = 99, repeats=10)
a

In [ ]:
a.reshape((2,5))

In [ ]:
# concatenate - Une un conjunto de arrays por filas o columnas

a = np.array([[1,2,3,4], [1,2,3,4]])
b = np.array([[4,3,2,1]])

print(a.shape)
print(b.shape)

In [ ]:
np.concatenate((a,b), axis = 0)

In [ ]:
np.concatenate((a.T, b.T), axis=1)

In [ ]:
# stack - Parecido a join, pero genera un nuevo indice
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

np.stack(arrays=(a,b), axis = 1)

In [ ]:
np.stack(arrays=(a,b), axis = 0)

In [ ]:
# split - Divide un array en varios
a = np.arange(0, 20)
a

In [ ]:
np.split(a, indices_or_sections=4)

In [46]:
np.split(a, [3, 5, 10, 16])

[array([1, 2, 3]),
 array([4]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]

In [45]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [47]:
np.insert(a, obj=4, values=[5,6])


array([1, 2, 3, 4, 5, 6])

In [48]:
np.insert(a, obj=1, values=[5,6])

array([1, 5, 6, 2, 3, 4])

In [49]:
# append - Inserta elementos al final del array
np.append(a, [5,6])

array([1, 2, 3, 4, 5, 6])

In [50]:
# delete - Elimina un elemento del array
np.delete(a, obj = 3)

array([1, 2, 3])

In [51]:
# trim_zeros - Elimina los 0s al inicio y el final del array
a = np.array([0, 0, 0, 0, 1, 2, 3, 4, 0, 0])
np.trim_zeros(a)

array([1, 2, 3, 4])

In [52]:
# unique - Deja los elementos unicos del array
a = np.array([1,1,1,1,2,2,2,2,3,3,3,3])
np.unique(a)

array([1, 2, 3])