In [1]:
import numpy as np

In [2]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [4]:
# identity - Devuelve un array identidad
np.identity(4, dtype = 'int8')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [6]:
# ones - Devuelve un array de unos. Podemos definir su dimension
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# zeros - Devuelve un array de zeros. Podemos definir su dimension
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# full - Devuelve una nueva matriz de forma y tipo dados, rellena con fill_value.
np.full(shape=(4,4), fill_value=99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [9]:
np.full(shape=(4,4), fill_value=[10,20,30,40])


array([[10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40]])

In [10]:
# fromstring - Una nueva matriz 1-D inicializada a partir de datos de texto en una cadena.
np.fromstring('1 2 3 4' , sep = ' ')

array([1., 2., 3., 4.])

In [13]:
datos = np.loadtxt('datos.txt', delimiter=' ', )
datos

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [14]:
# arange - Devuelve un array de los valores existentes en un invervalo definido. Podemos
# configurar el tamaño del paso
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [15]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [16]:
# linspace - Devuelve un número de valores entre un intervalo
np.linspace(start=1, stop=10, num = 5, endpoint=False, retstep=True)

(array([1. , 2.8, 4.6, 6.4, 8.2]), 1.8)

In [17]:
np.linspace(start=2, stop= 3.5, num = 10)


array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        , 3.16666667, 3.33333333, 3.5       ])

In [18]:
# logspace - Igual, pero aplicando una escala logaritmica
np.logspace(start=2, stop= 3.5, num = 10)

array([ 100.        ,  146.77992676,  215.443469  ,  316.22776602,
        464.15888336,  681.29206906, 1000.        , 1467.79926762,
       2154.43469003, 3162.27766017])

np.logspace(start=2, stop=3.5, num=10)
- 10 ** 2 = 100
- 10 ** 2.166667 = 146.779
- 10 ** 2.333333 = 215.443

In [19]:
# diag - Extrae la diagonal de una matriz o array de dos dimensiones

a = np.eye(N = 4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.diag(a)


array([1., 1., 1., 1.])

In [21]:
np.diag(a, k = 1)


array([0., 0., 0.])

In [22]:
# diagflat - Crea una matriz bidimensional con la entrada usada como diagonal.
np.diagflat(v = [1,2,3,4], k = 0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
np.diagflat(v = [1,2,3,4], k = -1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [24]:
np.tri(N = 5, M = 5)


array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [25]:
a = np.array([[1,2,3,4], [4,3,2,1]])
np.asmatrix(a)

matrix([[1, 2, 3, 4],
        [4, 3, 2, 1]])